<?php $_product = Mage::registry('current_product') ?>
<?php if ($_product && $_product->getId()): ?>
<!--this is your pop-up ring sizer magic : put this on the bottom of your page before your <\body> tag -->
<!--FMRS-POPUP:BEGIN -->
<script type='text/javascript'>
    var host = (("https:" == document.location.protocol) ? "https://" : "http://"); document.write(unescape("%3Cscript src='" + host + "findmyringsize.com/Shared/Embed/fmrs-1.0.js' type='text/javascript'%3E%3C/script%3E"));	
</script>

<script>
    var ringsizer = new FMRS();
    ringsizer.initialize({
        'client': 'sizer',
        'mode': 'overlay',
        'overlaySettings': { boxTheme: 'facebook', shadowOverlay: true }
    });
    ringsizer.bind();
</script>

<!--FMRS-POPUP:END-->

<?php endif; ?>